### ISSUE TITLE
[Data] Generar Preguntas para Archivo JSON

### ISSUE THREAD

**Issue by danielctecla** [mvnueloc/DevInterview#1]
**Descripción:**
Generar un conjunto de preguntas técnicas para tres roles (Software Developer, Frontend Developer, Backend Developer) y tres niveles de dificultad (Intern, Junior, Senior). Estas preguntas serán almacenadas en un archivo JSON estructurado.

**Tareas:**
- [x] Definir para cada combinación de rol y dificultad.
  - **Software Developer**
    - Intern
    - Junior
    - Senior
  - **Frontend Developer**
    - Intern
    - Junior
    - Senior
  - **Backend Developer**
    - Intern
    - Junior
    - Senior
- [x] Estructurar las preguntas en un archivo JSON.
- [x] Validar la correcta estructuración del archivo JSON.

**Formato del Archivo JSON:**
```json
{
  "roles": {
    "software_developer": {
      "intern": [
        {
          "question": "¿Qué es una variable en programación?",
        },
      ],
      "junior": [
        {
          "question": "Explica la diferencia entre una clase y un objeto.",
        },
      ],
      "senior": [
        {
          "question": "¿Cómo implementarías un patrón de diseño Singleton en tu lenguaje preferido?",
        },
      ]
    },
    "frontend_developer": {
      "intern": [
        {
          "question": "¿Qué es HTML?",
          "options": ["A", "B", "C", "D"],
          "answer": "A"
        },
      ],
     
     }
   }
}
```

**Notas Adicionales:**
- Las preguntas deben ser relevantes y específicas para el rol y nivel de dificultad.
- Revisar y verificar la consistencia y exactitud de las preguntas antes de finalizar.

**Comment by Antxnszn** [comment]
Notion de las preguntas para el json
https://amenable-peridot-d9e.notion.site/Vercel-Questions-706cb852e0f24d7cb4143953e60c2529?pvs=4
